steps:
  # 1️⃣ Побудувати Docker-образ
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'europe-west1-docker.pkg.dev/telegram-webhook-468010/webhooks/webhook-fastapi',
        '.'
      ]

  # 2️⃣ Запушити образ у Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'europe-west1-docker.pkg.dev/telegram-webhook-468010/webhooks/webhook-fastapi'
      ]

  # 3️⃣ Деплой у Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'webhook-fastapi',
        '--image', 'europe-west1-docker.pkg.dev/telegram-webhook-468010/webhooks/webhook-fastapi',
        '--platform', 'managed',
        '--region', 'europe-west1',
        '--allow-unauthenticated',
        '--port', '8080'
      ]

images:
  - europe-west1-docker.pkg.dev/telegram-webhook-468010/webhooks/webhook-fastapi

options:
  logging: CLOUD_LOGGING_ONLY
